version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: my-timescaledb
    environment:
      POSTGRES_DB: timeseries
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "2432:2432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    mem_limit: 4g
    cpus: 2
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: my-fastapi
    ports:
      - "2100:2100"
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      DB_HOST: timescaledb
      DB_PORT: 2432
      DB_NAME: timeseries
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./app:/app

volumes:
  pgdata:
